files:
  - source: /content/en/*.md
    translation: /content/%two_letters_code%/%original_file_name%
  - source: /content/en/community
    translation: /content/%two_letters_code%/community/%original_file_name%
  - source: /content/en/getting-started
    translation: /content/%two_letters_code%/getting-started/%original_file_name%
  - source: /content/en/reference/*.md
    translation: /content/%two_letters_code%/reference/%original_file_name%
  - source: /content/en/reference/client
    translation: /content/%two_letters_code%/reference/client/%original_file_name%
  - source: /content/en/examples
    translation: /content/%two_letters_code%/examples/%original_file_name%
